/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mahasiswabaru;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import static mahasiswabaru.Admin.DB_URL;
import static mahasiswabaru.Admin.JDBC_DRIVER;
import static mahasiswabaru.Admin.PASS;
import static mahasiswabaru.Admin.USER;
import static mahasiswabaru.Admin.conn;
import static mahasiswabaru.Admin.stmt;

/**
 *
 * @author Naufal Arsyaputra Pradana
 */
public class Formulir extends javax.swing.JFrame {

    /**
     * Creates new form formulir
     */
    public Formulir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        nisn = new javax.swing.JLabel();
        prodi = new javax.swing.JLabel();
        asal = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        txtNisn = new javax.swing.JTextField();
        txtProdi = new javax.swing.JTextField();
        txtAsal = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        keluar = new javax.swing.JMenuItem();
        tabel = new javax.swing.JMenu();
        mahasiswa = new javax.swing.JMenuItem();
        asal1 = new javax.swing.JMenuItem();
        prodi1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        judul.setText("Pendaftaran Mahasiswa");

        nama.setText("Nama");

        nisn.setText("NISN");

        prodi.setText("Minat Program Studi");

        asal.setText("Asal Sekolah");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        txtProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdiActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jMenu1.add(keluar);

        jMenuBar1.add(jMenu1);

        tabel.setText("Tabel");

        mahasiswa.setText("Mahasiswa Baru");
        mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mahasiswaActionPerformed(evt);
            }
        });
        tabel.add(mahasiswa);

        asal1.setText("Asal Sekolah");
        asal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asal1ActionPerformed(evt);
            }
        });
        tabel.add(asal1);

        prodi1.setText("Prodi Minat");
        prodi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodi1ActionPerformed(evt);
            }
        });
        tabel.add(prodi1);

        jMenuBar1.add(tabel);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(btnSubmit)
                .addGap(0, 287, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(judul)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(nisn))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNisn)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodi)
                            .addComponent(asal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdi)
                            .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(judul)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nisn)
                    .addComponent(txtNisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodi)
                    .addComponent(txtProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(asal))
                .addGap(26, 26, 26)
                .addComponent(btnSubmit)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String nama = txtNama.getText().toString().trim();
        int nisn = Integer.parseInt(txtNisn.getText());
        String minat = txtProdi.getText();
        String asal = txtAsal.getText();
        insert(nama, nisn, minat, asal);
        clear();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdiActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mahasiswaActionPerformed
        // TODO add your handling code here:
        new Mahasiswa().setVisible(true);
    }//GEN-LAST:event_mahasiswaActionPerformed

    private void asal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asal1ActionPerformed
        // TODO add your handling code here:
        new Sekolah().setVisible(true);
    }//GEN-LAST:event_asal1ActionPerformed

    private void prodi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodi1ActionPerformed
        // TODO add your handling code here:
        new Prodi().setVisible(true);
    }//GEN-LAST:event_prodi1ActionPerformed

    public void insert(String nama, int nisn, String minat, String asal) {
        try {
            Class.forName(JDBC_DRIVER);

            conn = DriverManager.getConnection(DB_URL, USER, PASS);

            stmt = conn.createStatement();

            String sql = "INSERT INTO mhs (nama, nisn, prodi, asal) VALUES (?,?,?,?)";

            PreparedStatement pms = conn.prepareStatement(sql);
            pms.setString(1, nama);
            pms.setInt(2, nisn);
            pms.setString(3, minat);
            pms.setString(4, asal);

            pms.execute();

            stmt.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clear() {
        // TODO add your handling code here:
        txtNama.setText("");
        txtNisn.setText("");
        txtProdi.setText("");
        txtAsal.setText("");
    }

    public String getNama() {
        return txtNama.getText().trim();
    }

    public int getNisn() {
        try {
            return Integer.parseInt(txtNisn.getText().trim());
        } catch (NumberFormatException e) {
            // Handle jika input tidak valid (misalnya tidak bisa di-parse ke int)
            e.printStackTrace();
            return 0; // Nilai default atau penanganan lainnya sesuai kebutuhan
        }
    }

    public String getProdi() {
        return txtProdi.getText().trim();
    }

    public String Asal() {
        return txtAsal.getText().trim();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asal;
    private javax.swing.JMenuItem asal1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel judul;
    private javax.swing.JMenuItem keluar;
    private javax.swing.JMenuItem mahasiswa;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nisn;
    private javax.swing.JLabel prodi;
    private javax.swing.JMenuItem prodi1;
    private javax.swing.JMenu tabel;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JTextField txtProdi;
    // End of variables declaration//GEN-END:variables
}
