/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mahasiswabaru;

/**
 *
 * @author Naufal Arsyaputra Pradana
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form front
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDaftar = new javax.swing.JButton();
        Judul = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        btnMhs = new javax.swing.JMenuItem();
        btnAsal = new javax.swing.JMenuItem();
        BtnProdi = new javax.swing.JMenuItem();
        btnKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDaftar.setText("Daftar Kuliah");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        Judul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Judul.setText("Pendaftaran Mahasiswa Baru");

        btnMenu.setText("Menu");

        btnMhs.setText("Tabel Mahasiswa");
        btnMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMhsActionPerformed(evt);
            }
        });
        btnMenu.add(btnMhs);

        btnAsal.setText("Tabel Asal Sekolah");
        btnAsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsalActionPerformed(evt);
            }
        });
        btnMenu.add(btnAsal);

        BtnProdi.setText("Tabel Program Studi");
        BtnProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProdiActionPerformed(evt);
            }
        });
        btnMenu.add(BtnProdi);

        menuBar.add(btnMenu);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        menuBar.add(btnKeluar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Judul)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnDaftar)))
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(Judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDaftar)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void BtnProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProdiActionPerformed

    private void btnMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMhsActionPerformed

    private void btnAsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BtnProdi;
    private javax.swing.JLabel Judul;
    private javax.swing.JMenuItem btnAsal;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JMenu btnKeluar;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JMenuItem btnMhs;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
